name: Fetch JSON

on:
  workflow_dispatch:
    inputs:
      user:
        required: true
        description: User name

jobs:
  fetch:
    name: Fetch JSON from Azure Storage
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - uses: suisei-cn/actions-download-file@v1
        name: Download the file
        with:
          url: https://stdfxapiloc.blob.core.windows.net/website/${{ github.event.comment.body }}.json
          target: src/website.json
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Commit the changes

